// Package version reports which build of Cardinal this is.
//
// Generated by `make version-file` from the VERSION file at the repository
// root, which is the single place the number is written. Do not edit by hand:
// `make bump-patch|bump-minor|bump-major` rewrites both.
//
// The number is a constant rather than an ldflag, deliberately. Before this
// existed .goreleaser.yaml passed `-X main.version={{.Version}}` to a symbol no
// package declared, and Go discards an -X for a symbol that does not exist —
// silently, with no warning and no build failure. So every release binary
// carried nothing, and would have gone on doing that indefinitely, because
// nothing anywhere asked a binary what it was.
//
// A constant cannot fail that way: if the generated file is missing, the build
// does not compile. Commit and Date are still ldflags because they are
// genuinely unknowable from the source tree, and they are allowed to be empty.
package version

// Number is the release this was built from.
const Number = "0.2.0"

// Commit and Date are stamped at link time by goreleaser. Empty in a local
// build, which is the honest answer rather than a guess.
var (
	Commit = ""
	Date   = ""
)

// String renders what a person should see: the number always, and the commit
// when there is one.
func String() string {
	if Commit == "" {
		return Number
	}
	short := Commit
	if len(short) > 7 {
		short = short[:7]
	}
	return Number + "+" + short
}
