package httpapi

import (
	"encoding/json"
	"errors"
	"net/http"
	"net/netip"
	"strings"

	"go.londer.be/cardinal/internal/store"
	"golang.org/x/crypto/ssh"
)

type hostEnrollRequest struct {
	Token string `json:"token"`

	// PublicKey is generated by the machine, so Cardinal never holds a host's
	// private key and cannot leak one it never had.
	PublicKey string `json:"publicKey"`
}

type hostEnrollResponse struct {
	Host        string `json:"host"`
	Fingerprint string `json:"fingerprint"`
	EnrolledAt  string `json:"enrolledAt"`
}

// handleHostEnroll registers the key a machine will authenticate with.
//
// Unauthenticated by necessity, exactly like a person redeeming an invitation:
// the whole point is that the caller has no credential yet. The token is the
// only thing authorising this, which is why it is single-use, short-lived, and
// spent by the same statement that reads it.
func (s *Server) handleHostEnroll(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var req hostEnrollRequest
	if err := json.NewDecoder(http.MaxBytesReader(w, r.Body, 64<<10)).Decode(&req); err != nil {
		writeError(w, http.StatusBadRequest, "could not read the request")
		return
	}

	req.Token = strings.TrimSpace(req.Token)
	if req.Token == "" || req.PublicKey == "" {
		writeError(w, http.StatusBadRequest, "token and publicKey are both required")
		return
	}

	publicKey, _, _, _, err := ssh.ParseAuthorizedKey([]byte(req.PublicKey))
	if err != nil {
		writeError(w, http.StatusBadRequest,
			"publicKey is not an SSH public key in authorized_keys form")
		return
	}

	var from netip.Addr
	if ip, err := netip.ParseAddr(s.clientIP.resolve(r)); err == nil {
		from = ip
	}

	cred, err := s.store.RedeemHostEnrollment(ctx, req.Token, publicKey, from)
	if err != nil {
		if errors.Is(err, store.ErrEnrollmentTokenInvalid) {
			// Deliberately does not say which of expired, spent, revoked or
			// never-existed. A machine that cannot enrol needs a new token
			// either way, and the distinction only helps someone guessing.
			writeError(w, http.StatusForbidden,
				"this enrollment token cannot be used — ask for a new one")
			return
		}
		s.log.ErrorContext(ctx, "host enrollment failed", "error", err)
		writeError(w, http.StatusInternalServerError, "could not enrol this host")
		return
	}

	s.log.InfoContext(ctx, "host enrolled",
		"host", cred.HostID, "fingerprint", cred.Fingerprint)

	writeJSON(w, http.StatusOK, hostEnrollResponse{
		Host:        cred.HostName,
		Fingerprint: cred.Fingerprint,
		EnrolledAt:  cred.EnrolledAt.UTC().Format("2006-01-02T15:04:05Z"),
	})
}

type hostSelfResponse struct {
	Host        string   `json:"host"`
	HostID      string   `json:"hostId"`
	Fingerprint string   `json:"fingerprint"`
	Groups      []string `json:"groups"`
	GroupIDs    []string `json:"groupIds"`
}

// handleHostSelf tells a host who Cardinal thinks it is.
//
// The first thing an agent calls, and the smallest possible proof that
// enrollment worked end to end: if this answers, the machine holds a key
// Cardinal recognises and signed a request with it.
//
// It returns group membership because that is what the agent's later questions
// are answered from — which sudoers rules apply, which POSIX identities to
// serve — and because a host that cannot see its own groups cannot tell whether
// a missing rule is a policy problem or a membership one.
func (s *Server) handleHostSelf(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	cred, ok := HostFrom(ctx)
	if !ok {
		writeError(w, http.StatusUnauthorized, "host authentication failed")
		return
	}

	subject, err := s.claims.ResolveByID(ctx, cred.HostID)
	if err != nil {
		s.log.ErrorContext(ctx, "resolving host memberships failed", "error", err)
		writeError(w, http.StatusServiceUnavailable, "could not resolve this host")
		return
	}

	writeJSON(w, http.StatusOK, hostSelfResponse{
		Host:        cred.HostName,
		HostID:      cred.HostID.String(),
		Fingerprint: cred.Fingerprint,
		Groups:      subject.GroupNames(),
		// The stable identifiers too, for the same reason applications get
		// them: a name is for showing a person, an id is for branching on.
		GroupIDs: subject.GroupIDs(),
	})
}
