// Restores web/dist/.gitkeep after a build.
//
// //go:embed all:dist in web/embed.go does not compile if dist/ is missing, so
// the directory has to survive in a fresh clone even though every file vite
// writes into it is ignored. vite builds with emptyOutDir, which deletes the
// placeholder along with the old assets — and a `git add -A` after a build then
// quietly stages its removal.
//
// This has broken the build on a clean checkout twice. Restoring it here means
// the placeholder cannot go missing without someone deleting it on purpose.
import { writeFileSync, mkdirSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const target = resolve(dirname(fileURLToPath(import.meta.url)), '..', 'dist', '.gitkeep')
mkdirSync(dirname(target), { recursive: true })
writeFileSync(target, `Keeps this directory in git.

//go:embed all:dist in web/embed.go will not compile if dist/ does not exist,
so a fresh checkout must have it even though every file vite writes here is
ignored. Regenerated by web/scripts/keep-dist.mjs after every build, because
vite's emptyOutDir deletes it.
`)
