import {
  createRootRoute,
  createRoute,
  createRouter,
  lazyRouteComponent,
} from '@tanstack/react-router'
import { Skeleton } from '@/components/ui/skeleton'
import { AppShell } from '@/components/AppShell'

const rootRoute = createRootRoute({ component: AppShell })

// Written out rather than generated by a helper: TanStack Router's type safety
// comes from the literal path flowing into the route, and a helper taking
// `path: string` erases exactly that — navigation then compiles whatever you
// type, which is the one thing a typed router is for.
//
// Views are code-split. The initial bundle is the shell rather than every screen
// an administrator might eventually open.

const homeRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: '/',
  component: lazyRouteComponent(() => import('@/views/home'), 'HomeView'),
})

// Arrived at from a terminal, never from the navigation. It is the one screen
// whose usual correct answer is "no", so it deliberately has no menu entry —
// somebody finding it by browsing has nothing to approve.
const cliLoginRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: '/cli-login',
  component: lazyRouteComponent(() => import('@/views/cli-login'), 'CLILoginView'),
})

const accountRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: '/account',
  component: lazyRouteComponent(() => import('@/views/account'), 'AccountView'),
})

const passkeysRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: '/access/passkeys',
  component: lazyRouteComponent(() => import('@/views/passkeys'), 'PasskeysView'),
})

const tokensRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: '/access/tokens',
  component: lazyRouteComponent(() => import('@/views/tokens'), 'TokensView'),
})

const connectedRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: '/access/connected',
  component: lazyRouteComponent(() => import('@/views/connected'), 'ConnectedView'),
})

const decisionsRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: '/access/decisions',
  component: lazyRouteComponent(() => import('@/views/decisions'), 'DecisionsView'),
})

const usersRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: '/directory/people',
  component: lazyRouteComponent(() => import('@/views/users'), 'UsersView'),
})

const userDetailRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: '/directory/people/$login',
  component: lazyRouteComponent(() => import('@/views/user-detail'), 'UserDetailView'),
})

const groupsRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: '/directory/groups',
  component: lazyRouteComponent(() => import('@/views/groups'), 'GroupsView'),
})

const groupDetailRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: '/directory/groups/$name',
  component: lazyRouteComponent(() => import('@/views/group-detail'), 'GroupDetailView'),
})

const hostsRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: '/directory/hosts',
  component: lazyRouteComponent(() => import('@/views/hosts'), 'HostsView'),
})

const hostDetailRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: '/directory/hosts/$name',
  component: lazyRouteComponent(() => import('@/views/host-detail'), 'HostDetailView'),
})

const applicationsRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: '/integrations/applications',
  component: lazyRouteComponent(() => import('@/views/applications'), 'ApplicationsView'),
})

const policyRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: '/policy',
  component: lazyRouteComponent(() => import('@/views/policy'), 'PolicyView'),
})

const auditRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: '/audit',
  component: lazyRouteComponent(() => import('@/views/audit'), 'AuditView'),
})

const authoritiesRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: '/authorities',
  component: lazyRouteComponent(() => import('@/views/authorities'), 'AuthoritiesView'),
})

const recoveryRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: '/directory/recovery',
  component: lazyRouteComponent(() => import('@/views/recovery'), 'RecoveryView'),
})

const routeTree = rootRoute.addChildren([
  homeRoute,
  cliLoginRoute,
  accountRoute,
  passkeysRoute,
  tokensRoute,
  connectedRoute,
  decisionsRoute,
  usersRoute,
  userDetailRoute,
  groupsRoute,
  groupDetailRoute,
  hostsRoute,
  hostDetailRoute,
  applicationsRoute,
  policyRoute,
  auditRoute,
  authoritiesRoute,
  recoveryRoute,
])

export const router = createRouter({
  routeTree,
  defaultPreload: 'intent',
  scrollRestoration: true,
  defaultPendingComponent: () => <Skeleton className="h-64 w-full" />,
})

declare module '@tanstack/react-router' {
  interface Register {
    router: typeof router
  }
}
