import {
  createRootRoute,
  createRoute,
  createRouter,
  lazyRouteComponent,
} from '@tanstack/react-router'
import { Skeleton } from '@/components/ui/skeleton'
import { AppShell } from '@/components/AppShell'

const rootRoute = createRootRoute({ component: AppShell })

// Written out rather than generated by a helper: TanStack Router's type safety
// comes from the literal path flowing into the route, and a helper taking
// `path: string` erases exactly that — navigation then compiles whatever you
// type, which is the one thing a typed router is for.
//
// Views are code-split. The initial bundle is the shell rather than every screen
// an administrator might eventually open.

const accountRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: '/',
  component: lazyRouteComponent(() => import('@/views/account'), 'AccountView'),
})

const passkeysRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: '/passkeys',
  component: lazyRouteComponent(() => import('@/views/passkeys'), 'PasskeysView'),
})

const connectedRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: '/connected',
  component: lazyRouteComponent(() => import('@/views/connected'), 'ConnectedView'),
})

const decisionsRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: '/decisions',
  component: lazyRouteComponent(() => import('@/views/decisions'), 'DecisionsView'),
})

const usersRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: '/admin/users',
  component: lazyRouteComponent(() => import('@/views/users'), 'UsersView'),
})

const userDetailRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: '/admin/users/$login',
  component: lazyRouteComponent(() => import('@/views/user-detail'), 'UserDetailView'),
})

const groupsRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: '/admin/groups',
  component: lazyRouteComponent(() => import('@/views/groups'), 'GroupsView'),
})

const groupDetailRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: '/admin/groups/$name',
  component: lazyRouteComponent(() => import('@/views/group-detail'), 'GroupDetailView'),
})

const applicationsRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: '/admin/applications',
  component: lazyRouteComponent(() => import('@/views/applications'), 'ApplicationsView'),
})

const recoveryRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: '/admin/recovery',
  component: lazyRouteComponent(() => import('@/views/recovery'), 'RecoveryView'),
})

const routeTree = rootRoute.addChildren([
  accountRoute,
  passkeysRoute,
  connectedRoute,
  decisionsRoute,
  usersRoute,
  userDetailRoute,
  groupsRoute,
  groupDetailRoute,
  applicationsRoute,
  recoveryRoute,
])

export const router = createRouter({
  routeTree,
  defaultPreload: 'intent',
  scrollRestoration: true,
  defaultPendingComponent: () => <Skeleton className="h-64 w-full" />,
})

declare module '@tanstack/react-router' {
  interface Register {
    router: typeof router
  }
}
