import type { SidebarsConfig } from '@docusaurus/plugin-content-docs'

/**
 * Written out rather than generated from the directory.
 *
 * Autogeneration would order these alphabetically, which puts the schema
 * reference before the walkthrough somebody needs first. The order below is the
 * order a new reader wants them in.
 */
const sidebars: SidebarsConfig = {
  docs: [
    'first-run',
    'architecture',
    'integration',
    'certificate-authorities',
    'threat-model',
    'comparison',
    'schema',
    {
      type: 'category',
      label: 'Decisions',
      description:
        'Why things are the way they are. Recorded so the reasoning does not ' +
        'have to be relitigated in six months.',
      // docs/adr/README.md rather than a generated index: it explains what an
      // ADR is and why these are kept, which no generated page would.
      link: { type: 'doc', id: 'adr/README' },
      items: [{ type: 'autogenerated', dirName: 'adr' }],
    },
  ],
}

export default sidebars
